name: bright-api-incremental-scan

on:
  workflow_call:
    inputs:
      archive_path:
        required: true
        type: string
      scan_name:
        required: false
        type: string
        default: "Incremental API Scan"
    secrets:
      BRIGHT_API_TOKEN:
        required: true
      BRIGHT_PROJECT_ID:
        required: true
      KEY_GITHUB:
        required: true

jobs:
  bright_api_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload OpenAPI/Swagger file using Bright CLI
        id: upload
        run: |
          archive_path="${{ inputs.archive_path }}"
          archive_id=$(docker run --rm -v "$PWD:$PWD" -w "$PWD" brightsec/cli archive:upload --type openapi --token "${{ secrets.BRIGHT_API_TOKEN }}" --project-id "${{ secrets.BRIGHT_PROJECT_ID }}"   "$archive_path")

          if [ -z "$archive_id" ]; then
            echo "::error::Failed to upload archive."
            exit 1
          fi
          echo "file_id=$archive_id" >> $GITHUB_OUTPUT

      - name: Run Discovery
        id: discovery
        uses: NeuraLegion/bright-github-actions/run-discovery@release
        with:
          api_token: ${{ secrets.BRIGHT_API_TOKEN }}
          project_id: ${{ secrets.BRIGHT_PROJECT_ID }}
          discovery_types: |
            [ "oas" ]
          file_id: ${{ steps.upload.outputs.file_id }}

      - name: Wait for Discovery to Complete
        uses: NeuraLegion/bright-github-actions/wait-for-discovery@release
        with:
          api_token: ${{ secrets.BRIGHT_API_TOKEN }}
          discovery_id: ${{ steps.discovery.outputs.id }}
          project_id: ${{ secrets.BRIGHT_PROJECT_ID }}
          timeout: 600

      - name: List New/Changed Entry Points
        id: list_eps
        uses: NeuraLegion/bright-github-actions/list-entrypoints@v1
        with:
          api_token: ${{ secrets.BRIGHT_API_TOKEN }}
          project_id: ${{ secrets.BRIGHT_PROJECT_ID }}
          status: new

      - name: Fail if No Entry Points Found
        if: ${{ steps.list_eps.outputs.entrypoints == '[]' }}
        run: |
          echo "::error::No new or changed entry points found. Skipping scan."
          exit 1

      - name: Run Vulnerability Scan
        id: scan
        uses: NeuraLegion/bright-github-actions/run-scan@release
        with:
          api_token: ${{ secrets.BRIGHT_API_TOKEN }}
          project_id: ${{ secrets.BRIGHT_PROJECT_ID }}
          name: "${{ inputs.scan_name }} - ${{ github.run_id }}"
          entrypoints: ${{ steps.list_eps.outputs.entrypoints }}

      - name: Wait for Scan Completion
        uses: NeuraLegion/bright-github-actions/wait-for@release
        with:
          api_token: ${{ secrets.BRIGHT_API_TOKEN }}
          scan: ${{ steps.scan.outputs.id }}
          wait_for: any
          code_scanning_alerts: true
          github_token: ${{ secrets.KEY_GITHUB }}
          timeout: 900
